name: health_example
description: Demonstrates how to use the health plugin.
publish_to: "none"
version: 13.3.2

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^13.0.0
  carp_serializable: ^3.0.0 # polymorphic json serialization
  health:
    path: ../

dev_dependencies:
  flutter_lints: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # https://github.com/flutter/flutter/issues/186881
  config:
    enable-swift-package-manager: true
