name: health
description: Wrapper for Apple's HealthKit on iOS and Google's Health Connect on Android.
version: 13.3.1
homepage: https://github.com/carp-dk/carp-health-flutter

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.6.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  device_info_plus: '^13.1.0'
  json_annotation: ^4.12.0
  carp_serializable: ^2.0.1 # polymorphic json serialization

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Using carp_serializable & json_serializable to auto generate json code (.g files) with this command:
  #   dart run build_runner build --delete-conflicting-outputs
  build_runner: ^2.15.0
  json_serializable: ^6.14.0
  mocktail: ^1.0.5
  mockito: ^5.7.0

flutter:
  plugin:
    platforms:
      android:
        package: cachet.plugins.health
        pluginClass: HealthPlugin
      ios:
        pluginClass: HealthPlugin
